spring:
  application:
    name: table-service
  data:
    mongodb:
      database: test_db
      host: localhost
      port: 27017
      auto-index-creation: true


server:
  port: 8200

eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
